<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    
    <!-- Максимальное сжатие рантайма и отключение ненужных фоновых потоков -->
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
    <ServerGarbageCollector>false</ServerGarbageCollector>
    <InvariantGlobalization>true</InvariantGlobalization>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <TieredPGO>true</TieredPGO>
    
    <!-- Поддержка Native AOT (при сборке dotnet publish -c Release) -->
    <PublishAot>true</PublishAot>
    <StripSymbols>true</StripSymbols>
  </PropertyGroup>
</Project>
