<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>

    <!-- Меньше памяти и потоков в простое -->
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
    <ServerGarbageCollector>false</ServerGarbageCollector>
    <InvariantGlobalization>true</InvariantGlobalization>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <TieredPGO>true</TieredPGO>
  </PropertyGroup>
</Project>
