name: Release ClearTaskbar

on:
  push:
    tags:
      - 'v*'
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Publish Native AOT Executable
      run: >
        dotnet publish ClearTaskbar.csproj
        -c Release
        -r win-x64
        -p:PublishAot=true
        -o ./publish-aot

    - name: Rename binary
      run: |
        Move-Item ./publish-aot/ClearTaskbar.exe ./publish-aot/ClearTaskbar-aot.exe

    - name: Upload AOT Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ClearTaskbar-aot
        path: ./publish-aot/ClearTaskbar-aot.exe

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./publish-aot/ClearTaskbar-aot.exe
        generate_release_notes: true
